// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKRjyXCY2AeWQqgeH4odRDNk8ZpNv93KM',
    appId: '1:626174467526:web:728f3945523417e132a6c7',
    messagingSenderId: '626174467526',
    projectId: 'notenova-f5b65',
    authDomain: 'notenova-f5b65.firebaseapp.com',
    storageBucket: 'notenova-f5b65.appspot.com',
    measurementId: 'G-VXWYLFT6SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuJRJkdfqBvnUUNHTT3s1bBzHitA2Ye2c',
    appId: '1:626174467526:android:16f4fd6b526c683f32a6c7',
    messagingSenderId: '626174467526',
    projectId: 'notenova-f5b65',
    storageBucket: 'notenova-f5b65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP3RPwBB97Al6jZ9ecefROZSUDuFGeoh4',
    appId: '1:626174467526:ios:887ba3e04ba3ad2f32a6c7',
    messagingSenderId: '626174467526',
    projectId: 'notenova-f5b65',
    storageBucket: 'notenova-f5b65.appspot.com',
    iosBundleId: 'com.example.notenova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP3RPwBB97Al6jZ9ecefROZSUDuFGeoh4',
    appId: '1:626174467526:ios:887ba3e04ba3ad2f32a6c7',
    messagingSenderId: '626174467526',
    projectId: 'notenova-f5b65',
    storageBucket: 'notenova-f5b65.appspot.com',
    iosBundleId: 'com.example.notenova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKRjyXCY2AeWQqgeH4odRDNk8ZpNv93KM',
    appId: '1:626174467526:web:1739651416f9bfac32a6c7',
    messagingSenderId: '626174467526',
    projectId: 'notenova-f5b65',
    authDomain: 'notenova-f5b65.firebaseapp.com',
    storageBucket: 'notenova-f5b65.appspot.com',
    measurementId: 'G-JS26WN7NLC',
  );
}
